services:
  - type: web
    name: teacher-assistant-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health-check
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 